language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_SETTINGS_MODULE=test_app.settings
before_script:
  - flake8 rna
script: make cover
install:
  - pip install -r requirements/dev.txt --use-mirrors
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls --use-mirrors
  - coveralls
notifications:
  irc:
    channels:
      - "irc.mozilla.org#nucleus"
    on_success: change
    on_failure: always
    use_notice: true
